language: node_js
node_js:
  - "10"
notifications:
    email:
        recipients:
            - handsome841206@gmail.com
        on_success: always
        on_failure: always
install:
    - npm install
script:
    - npm start
